all: build/main
	./build/main

build/print-buffer.o: print-buffer.c
	@mkdir -p $(dir $@)
	$(CC) -c $< -o $@

build/main.o: main.c
	@mkdir -p $(dir $@)
	$(CC) -c $< -o $@

build/main: build/main.o build/print-buffer.o
	@mkdir -p $(dir $@)
	$(CC) -o $@ $^
